# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Education"
  url = "#education"
  weight = 20

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 30

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 40

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 41

[[main]]
  name = "publication"
  url = "#publications"
  weight = 44

[[main]]
  name = "Blog"
  url = "https://www.chaiheyan.space"
  weight = 51

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "Resume"
    url = "files/chaiheyan_Resume.pdf"
    weight = 70

# [[main]]
#   name = "中文"
#   url = "/zh/"
#   weight = 88

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
